extends: dvslip_predictive_s0.yaml

experiment:
  name: dvslip_predictive_s1

model:
  temporal_channel_mixer_surprise_routing: true
  temporal_channel_mixer_router_pooling: local
  temporal_channel_mixer_routing_stages: [2]
  temporal_channel_mixer_routing_parameterization: amplitude_allocation
