extends: dvslip_predictive_s0.yaml

experiment:
  name: dvslip_predictive_s0_dynamic

model:
  temporal_channel_mixer_dynamic_routing: true
  temporal_channel_mixer_router_pooling: local
  temporal_channel_mixer_router_hidden_divisor: 2
